webapps:
  - 10.0.99.3
  - 10.0.99.4

splunk:
  host: <?>
  port: <?>
  key_name: <?>
  index: main
  debug: False
  protocol: <?>
  verify: <?>
  flush: 0
  level: INFO
  retry_count: 5
  
files_output:
  folder: "/code/tmp"
  sanitized: "/code/tmp/sanitized"
  template: Template('$url-$timestamp')
  extensions: 
    - txt
    - xml
  extension_used: xml

logging:
  folder: "/code/tmp"
  file: webtentacle-debug.log
  mode: debug

nikto:
  useragent: webtentacle