version: '3.6'

services:
  splunkenterprise:
    hostname: splunkenterprise
    image: splunk/splunk:7.2.0
    restart: always
    user: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt --seed-passwd ${SPLUNK_INITIAL_PASSWORD}
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_ADD=tcp 1514
      - SPLUNK_UPGRADE=True
      - SPLUNK_PASSWORD=${SPLUNK_INITIAL_PASSWORD}
      - DEBUG=1
      - USER=root
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "8089:8089"
      - "1514:1514"
