version: '3'

volumes:
  opt-splunk-etc:
  opt-splunk-var:

services:
  #web:
  #  build: .
  splunkenterprise:
    #build: .
    hostname: splunkenterprise
    image: splunk/splunk:7.2.0
    environment:
      - SPLUNK_START_ARGS=--accept-license --no-prompt --answer-yes
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_ADD=tcp 1514
      - SPLUNK_USERNAME=admin
      - SPLUNK_PASSWORD=password
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"