version: '3.6'

volumes:
  opt-splunk-etc:
  opt-splunk-var:

services:
  #web:
  #  build: .
  splunkenterprise:
    hostname: splunkenterprise
    image: splunk/splunk:7.2.0
    restart: always
    user: root
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt --seed-passwd ${SPLUNK_INITIAL_PASSWORD}
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_ADD=tcp 1514
      - SPLUNK_UPGRADE=True
      - SPLUNK_PASSWORD=${SPLUNK_INITIAL_PASSWORD}
      - DEBUG=1
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "8089:8089"
      - "1514:1514"
