version: '3.6'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SPLUNK_API_KEY
        - SERVICE
        - SPLUNK_API_PASSWORD
        - SPLUNK_HOSTNAME
        - SPLUNK_PORT